### ISSUE TITLE
Korzystanie z icon na statycznej stronie

### ISSUE THREAD

**Issue by Dariuszsibik** [tomwilusz/lord-icon-element#1]
W jaki sposób, ewentualnie jakie biblioteki javascript potrzebuje, aby móc korzystać z ikon na stronie statycznej opartej o HTML, CSS, JS ?

**Comment by baszczewski** [comment]
Element zgodnie z opisem _README_ wymaga zainstalowania **dwóch bibliotek**: 
```bash
npm install lord-icon-element lottie-web
```
Te mogą być wygodnie zaimportowane jeśli używasz Webpack-a następująco:
```js
import { loadAnimation } from 'lottie-web';
import { defineLordIconElement } from 'lord-icon-element';

// register lottie and define custom element 
defineLordIconElement(loadAnimation);
```
Funkcja loadAnimation jest rejestrowana w obrębie naszego elementu przed jego użyciem. Dzięki temu końcowy element jest lekki (nie ma żadnych zależności do pobrania), a i końcowy użytkownik decyduje z jakiego sterownika rysowania animacji chce korzystać (lottie-web oferuje ich kilka, nie ma potrzeby wczytywania wszystkich na raz tym bardziej że te zajmują względnie sporo miejsca). Równocześnie gdyby Twoja strona korzystała już z "lottie-web" ta sama raz załadowana instancja może być wykorzystana w elemencie. 

Oczywiście jeśli nie korzystasz z Webpack-a nadal możesz skorzystać z tego elementu. Pamiętaj by zaimportować niezbędne biblioteki z poziomu HTML-a:
```html
<script type="module" src="./node_modules/lottie-web/build/player/lottie_svg.min.js"></script>
<script type="module" src="./node_modules/lord-icon-element/build/lord-icon-element.js"></script>
```
Projekt powstał z wykorzystaniem TypeScript-a. W repozytorium nie przechowuję jego zbudowanej postaci. Tą możesz pobrać z NPM-a. Możesz też zbudować całość samodzielnie. 

Zachęcam do zainstalowania całości i podejrzenia w akcji przykładów.

Element wspiera domyślnie nowoczesne przeglądarki, to jest zawierające wsparcie dla Web Components:
https://caniuse.com/#feat=custom-elementsv1

Instalując określone biblioteki ze wsparciem dla przestarzałych przeglądarek można by całość zmusić do pracy również ze starszymi przeglądarkami. Aktualnie jednak tego nie wspieramy.
