### ISSUE TITLE
Flexslider

### ISSUE THREAD

**Issue by mizzinc** [tomwilusz/lord-icon-element#13]
Hello, 

Using Lordicons in Flexslider.
Flexslider is blank unless scroll left/right and the icons flash, then vanish.

Do I need to initialize LordIcon again after scroll?

Thank you for any assistance you can provide.

**Comment by baszczewski** [comment]
Hi. Unfortunately I don't have idea what is wrong here. I can see some issues only on Chrome (Firefox is OK), and even not every time. 
For some reason in this use case our element don't trigger "registerLottie()" method which is important to display animation. If you have possibility to execute this method on "lord-icon" element this could be temporary solution. 

By the way. Could you provide basic example of your usage?

**Comment by mizzinc** [comment]
Thanks for your response. 
This is static implementation with only the lord-icon.js file enqueued.

Ill try whip up a basic example.

**Comment by mizzinc** [comment]
Included element.js. All resolved. Thank you.
