### ISSUE TITLE
"loadAnimation" errors in Angular and Vue

### ISSUE THREAD

**Issue by Socca98** [tomwilusz/lord-icon-element#17]
Hi!
Just npm installed 'lottie-web' and 'lord-icon-element'.
I google a lot, but I can't make a lordicon appear on my website.
**Angular**:
![a1](https://user-images.githubusercontent.com/39209079/108759886-9e186180-7555-11eb-9e92-3750890c9d25.png)
If I write ``` import loadAnimation from 'lottie-web'; ``` without curly braces, it throws:
```
TS2345: Argument of type 'LottiePlayer' is not assignable to parameter of type 'LottieLoader'.
```

**Vue**:
![a2](https://user-images.githubusercontent.com/39209079/108759908-a5d80600-7555-11eb-869b-25be8b66c34d.png)

**Comment by baszczewski** [comment]
Hi. Look here: #16
