### ISSUE TITLE
"<lord-icon>" not found

### ISSUE THREAD

**Issue by Socca98** [tomwilusz/lord-icon-element#18]
Hi!

Tried #16 . I don't know where to paste "lottie-web.d.ts".
Copy pasted it in some folders (src, node_modules, etc.) and added CUSTOM_SCHEMAS to 'app.module.ts', but in 'app.component.html' lordicon is unrecognized: "Unknown html tag lord-icon".

**Comment by baszczewski** [comment]
Read about TypeScript type definitions. Unfortunetlly "lottie-web" don't provide any types (and there is no library like @types/lottie-web), so file "lottie-web.d.ts" provide base definitions important for TS compilation. 

Own types files could be stored in many places. By default this could be main source directory where is tsconfig.json.

**Comment by Socca98** [comment]
A json icon is still not displayed due to unknown html tag.
In lottie-web.d.ts I have a `TSLint: 'namespace' and 'module' are disallowed(no-namespace)`. It shouldn't be a problem though.
I am reading here they may have been some changes after Angular 9, but can't figure it out:
https://stackoverflow.com/questions/39428132/custom-elements-schema-added-to-ngmodule-schemas-still-showing-error

![unknown tag](https://user-images.githubusercontent.com/39209079/108856000-4419a980-75f2-11eb-8ef6-e49b3de681b0.png)


![b2](https://user-images.githubusercontent.com/39209079/108858197-8f34bc00-75f4-11eb-8779-da4ad0c12d7d.png)

**Comment by baszczewski** [comment]
Remember about:
```ts
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
...
@NgModule({
    ...
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class MyModule {}
```

**Comment by Socca98** [comment]
Included it (second photo) below imports. 
The steps for bug: 
- generate an Angular project, npm install
- npm install lottie-web, lord-icon-element
- copy paste 'lottie-web.d.ts' in 'src' folder
- add custom schemas in 'app.module.ts' and a lord-icon html tag in 'app.component.html'
- add a lord icon json in 'src/app' folder

**Comment by baszczewski** [comment]
Could you share your project?

**Comment by Socca98** [comment]
https://we.tl/t-5VzqSGkwew

This is. Just needs npm install.

**Comment by Socca98** [comment]
https://we.tl/t-fYY2x7ym4j

This is. Just needs npm install.

**Comment by baszczewski** [comment]
Thanks for sample code. Your implementation is ok. But you have to move icon to other directory (for example to /assets) and update src path to it (alternative for that is some changes in angular.json).  

1. Move icon from _app_ directory to _assets_
2. Update _src_ property in lord-icon element (src="/assets/my-icon.json")

And voilà:
![image](https://user-images.githubusercontent.com/3357435/109144712-ce345000-7761-11eb-8bf4-013b3b555bfb.png)

**Comment by baszczewski** [comment]
PS
You can define custom element later in your module constructor. For example in one of my **Angular** project I have something like this:

```ts
@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SomeModule {
  constructor() {
    defineLordIconElement(loadAnimation);
  }
}
```

PS2
For fancy use cases of this element look for our examples:
https://github.com/tomwilusz/lord-icon-element/tree/master/examples

**Comment by Menencia** [comment]
Where can I find 'lottie-web.d.ts' file ?

**Comment by baszczewski** [comment]
> Where can I find 'lottie-web.d.ts' file ?

This topic talks about past state. At the moment _lottie-web_ contains build in _TypeScript declarations_.
