### ISSUE TITLE
Usage Trouble

### ISSUE THREAD

**Issue by heyitsliv** [tomwilusz/lord-icon-element#19]
Hi there

This may be a newbie-question and I don't even know if this is the right place to ask it (if it's not, feel free to delete this).
I tried to implement the lord-icon-element via npm into my own website by following your instructions in the Readme-file but i keep getting this error message about my code in the script module:

**script.js**
```
  import { loadAnimation } from "./node_modules/lottie-web/build/player/lottie.js";
  import { defineLordIconElement } from "./node_modules/lord-icon-element/build/lord-icon-element.js";

  // register lottie and define custom element
  defineLordIconElement(loadAnimation);
```

**error message**
_Uncaught SyntaxError: The requested module './node_modules/lottie-web/build/player/lottie.js' does not provide an export named 'loadAnimation'_ (Browser: Chrome)

Do you have an idea what I did wrong? Again, I'm pretty new to using node.js & npm. 
Any help would be appreciated, thank you!

**Comment by baszczewski** [comment]
Hi. Could you share your project?

**Comment by livtonkins** [comment]
Unfortunately, I'm not allowed to share the whole project, but I recreated my problem here, if that helps?
https://681848-10.web1.fh-htwchur.ch/

**Comment by baszczewski** [comment]
I don't need a whole project but minimal example.

**Comment by heyitsliv** [comment]
Okay, so is the link enough? Or did you mean load the code on github? https://github.com/livtonkins/Test-Project

**Comment by baszczewski** [comment]
I don't see here any http server which is important to load correctly some local resources and JS modules. 

If you need easy integration just use released version of library:
https://github.com/tomwilusz/lord-icon-element/tree/master/bin
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/without-modules.html


Remember that assets bunder is better solution here (for example webpack).

**Comment by heyitsliv** [comment]
Okay, thank you! I'll look into that.

Edit: I just tried the easy integration method, works just the way I needed it to. Didn't know there was such an easy way, I guess I gotta lot to learn. Thanks for your help!
