### ISSUE TITLE
Change the color of the icons

### ISSUE THREAD

**Issue by Dariuszsibik** [tomwilusz/lord-icon-element#2]
It would be possible to change the default colours of icons?
During importing the json file according to the documentation, all icons have the colors # 121331, RGB (18, 19, 49) and # 30B37E RGB (48, 179, 126).
I would like to replace the colors of these icons with the other ones, for example # 0000FF and # 000000.
How can I do this?
would you be so kind and provie me an example of code?

**Comment by baszczewski** [comment]
Example for this is already [provided](https://github.com/tomwilusz/lord-icon-element/blob/master/examples/example4.html).

**Comment by alienbuild** [comment]
The link above is dead. I managed to figure it out though by looking through all of the examples and seeing there is a `palette` prop that can be passed in. Is there documention somewhere for all props that can be passed into lord-icon? particuarly looking for a size attribute if possible.

Thanks,

**Comment by alienbuild** [comment]
Managed to find the supported attributes.

```
const OBSERVED_ATTRIBUTES = [
    'palette',
    'src',
    'icon',
    'animation',
    'speed',
    'target',
    'params',
];
```

Unfortunately size isn't one of them.

However easy to add if any one else is also requiring the same. Include 'size' in the above OBSERVED_ATTRIBUTES, then proceed to edit line 75 (i think, look for style.innerHTML if not) of element.js to be the following:
```
       style.innerHTML = `
            :host {
                display: inline-flex;
                width: ${this.size};
                height: ${this.size};
                align-items: center;
                justify-content: center;
                position: relative;
                vertical-align: middle;
                fill: currentcolor;
                stroke: none;
                overflow: hidden;
            }
        
            svg {
                pointer-events: none;
                display: block;
            }
        
            div {    
                width: 100%;
                height: 100%;
            }
        
            div.slot {
                position: absolute;
                left: 0;
                top: 0;
                z-index: 2;
            }
        `;
```

Then in your component just pass in the size attribute ie: 
```
<lord-icon animation="hover" size={'200px'} palette="#03a9f4" src={`./assets/icons/1-cloud/1-cloud-outline.json`}></lord-icon>
```

**Comment by baszczewski** [comment]
@alienbuild 
Hi. The best way to resize lord-icon element is just use the CSS (width + height). Of course you can use here style tag and attribute as you prefer. Provide support for "size" attribute is in my opinion redundant idea. 

Link was changed some time ago:
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/dynamic-customization.html

We don't have single place with description of all supported attributes.

**Comment by alienbuild** [comment]
CSS would be great if it accepted a classname prop (thinking mostly of using in a react setup here), otherwise it requires additional markup just to wrap the icon in a class which isn't ideal and just crowds the markup. Additionally the labour of also adding extra code for css and classes can be avoided by supporting a size prop, just as fontawesome's and other popular icon packages do. 

I'm not sure if it's a redundant idea, maybe in some cases? But at least for my use case it would be more efficient.

**Comment by baszczewski** [comment]
You can use class name here. There is no need for any kind of wrap.

**Comment by alienbuild** [comment]
Thanks, do you have an example of that? I did try to pass in 'className' as a prop but it didn't seem to do anything and isn't in the OBSERVED_ATTRIBUTES code block so assumed it wasn't supported.

Thanks,

**Comment by baszczewski** [comment]
Example:
```html
<style>
.big { width: 256px; height: 256px; }
</style>

<lord-icon class="big"></lord-icon>
```

**Comment by alienbuild** [comment]
That worked, thank you.
