### ISSUE TITLE
Morph trigger, but on click

### ISSUE THREAD

**Issue by piercegearhart** [tomwilusz/lord-icon-element#23]
Hello, I am using lord-icons with my html website, and I am wanting to use the menu icon for a mobile menu. Morph is the perfect option, since when I hover it transforms to the "X" and when I stop hovering it goes back to the menu Icon. My question is, is there anyway I can make it morph on click? So when I click the icon it transforms into the "X' and when I click it again it transforms into the regular menu Icon?

**Comment by jondeodat** [comment]
I also have the same use case. I would like to switch between two states on click. Thus clicking once  trigger the animation. Clicking again play the animation backward (not forward from the beginning).

**Comment by baszczewski** [comment]
There is already example for that:
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/custom-triggers.js
