### ISSUE TITLE
Using variables for primary and secondary colors

### ISSUE THREAD

**Issue by sammypanda** [tomwilusz/lord-icon-element#25]
I've tried a couple different methods for trying to use CSS variables for secondary and primary.

The only other option it looks like I have is inherit-color but that just sets it as one colour only :( 

Thank you! :heart:

**Comment by baszczewski** [comment]
Some icons will support css variables soon. Demo for that: https://github.com/tomwilusz/lord-icon-element/blob/master/demo/css-variables.html
