### ISSUE TITLE
Reverse loop

### ISSUE THREAD

**Issue by kctdfh** [tomwilusz/lord-icon-element#26]
Hey I want to use the "interface slider" for a slider that turns left (the icon animation shows the slider turn right) and wanted to reverse the animation on loop mode. Can this be done? Couldn't find anything on the docs and on Github. Thanks

**Comment by baszczewski** [comment]
Of course you can implement something like this with **custom trigger**. 

Maybe our samples with help you in implementation: https://lordicon.com/help/32-web-lordicon-custom-element (_Click me twice trigger_).

**Comment by bumpyy** [comment]
> Of course you can implement something like this with **custom trigger**.
> 
> Maybe our samples with help you in implementation: [lordicon.com/help/32-web-lordicon-custom-element](https://lordicon.com/help/32-web-lordicon-custom-element) (_Click me twice trigger_).

it didn't work for me, i'm using react with vite

**Comment by baszczewski** [comment]
> > Of course you can implement something like this with **custom trigger**.
> > Maybe our samples with help you in implementation: [lordicon.com/help/32-web-lordicon-custom-element](https://lordicon.com/help/32-web-lordicon-custom-element) (_Click me twice trigger_).
> 
> it didn't work for me, i'm using react with vite

Could you provide some details here?
