### ISSUE TITLE
Change Color in dark Mode 

### ISSUE THREAD

**Issue by katche70** [tomwilusz/lord-icon-element#28]
Hi, 

it's possible to change load-icon color over css file? 
It's important to play with color in dark Mode 
`@media (prefers-color-scheme: dark)`

**Comment by baszczewski** [comment]
Yes. It's possible but only for icons which supports _css variables_ (system icons family, [example](https://github.com/tomwilusz/lord-icon-element/blob/master/demo/css-variables.html
)).

For other icons this will be difficult (you can create [own icon loader](https://github.com/tomwilusz/lord-icon-element/blob/master/demo/preload-icon.js) with custom JS handler for light / dark mode).
