### ISSUE TITLE
Support for lottie-lite

### ISSUE THREAD

**Issue by markmcdowell** [tomwilusz/lord-icon-element#32]
Hello! the icons look great and we integrated them ok but the lottie player uses eval in their code which then creates a security issue. 

I tried switching to the lottie lite player (see https://github.com/airbnb/lottie-web/issues/289) which almost works but the icons are offset and I don't seem to be able to correct them.

Any chance of getting them to work with the non-eval version?

**Comment by baszczewski** [comment]
Unfortunately in our custom element, we need all _lottie-web_ features, especially _expressions_ which needs eval to work. 
However if you don't need support for dynamic properties (switching colors etc), our triggers, states, you can use raw json files with _lottie-lite_ directly.

**Comment by markmcdowell** [comment]
Perfect works fine with the raw json (with a couple of tweaks to the layers).

Thanks!

**Comment by baszczewski** [comment]
By the way: you can colorize (customize) raw icons with some web tools (https://lottiefiles.com/). There is also project file provided which allows almost everything. 
Raw files is extreme helpful on mobile devices and another usage outside web browser.
