### ISSUE TITLE
Updating to 3.4.3 causing an issue with custom Triggers

### ISSUE THREAD

**Issue by minaalfy** [tomwilusz/lord-icon-element#34]
After updating from 3.4.2 to 3.4.3 it cause an issue with the colors, it doesn't read what we pass and only render with default color

**Comment by baszczewski** [comment]
Could you provide some details? Example usage and icon name will be appreciated.

**Comment by minaalfy** [comment]
We're using lord-icon to display 3 icons each one of it has 2 states the first state to be animated while icon start being in screen and other one for hover state.

one of it is a charging station
`{file: 'charging-outline.json', trigger: 'morph-two-way', state: 'Morph' }`
We've defined a custom InScreenTrigger and using it for the `in screen` state.
Then pass the trigger and state properties as in the above json.

This setup completely working with the previous version however after upgrading to 3.4.3 it's missed up as all colors disappears.

I hope this information is enough

**Comment by baszczewski** [comment]
Could you provide here any reproducible code? Like https://stackblitz.com/edit/lord-icon-in-screen-trigger?file=index.js
