### ISSUE TITLE
The package is not caching anymore

### ISSUE THREAD

**Issue by DaanMoura** [tomwilusz/lord-icon-element#37]
I updated the package from 3.4.3 to 4.0.1 and it seems that it is not caching anymore. The previous version used to cache, so once the icon is loaded, there is no need to load the same icon again. But in the new version, it seems that it is not happening anymore, every time I change the page, new requests are made to load icons that have been loaded before, making the icon flash.

**Comment by baszczewski** [comment]
> I updated the package from 3.4.3 to 4.0.1 and it seems that it is not caching anymore. The previous version used to cache, so once the icon is loaded, there is no need to load the same icon again.

Browsers has built in cache funcionality which is configured by developers with response headers (like cache-control, etc.). Our project handle this out of box for icons and library loaded from CDN.
This means that loaded icons can be cached on user hard drive and used again on future visits without additional network traffic:  

![image](https://user-images.githubusercontent.com/3357435/204750287-6c0dd19f-be2b-44cc-9ae2-bb6f4f0d8692.png)

> But in the new version, it seems that it is not happening anymore, every time I change the page, new requests are made to load icons that have been loaded before, making the icon flash.

What we changed in 4.X version is icon loading strategy. Now every usage of icon is single request to server, even when icons shares same src. So we cut off some kind of cache which was previously negative impact for huge "single page apps" where cache not allow us to free memory of unused icons.
If this is a reason of your observation you can mimic old behavior by our API which was redefined, simplified and now is a lot more extensibile. For example you can provide own icon loader:

- example: https://stackblitz.com/edit/lord-icon-icon-loader?file=index.js
- docs: https://element.lordicon.com/classes/element.Element.html#setIconLoader

**Comment by DaanMoura** [comment]
Thanks!! It's good to know about this custom icon loader. It will solve the problem.
