### ISSUE TITLE
Trying to use in React/Gatsby but renders nothing

### ISSUE THREAD

**Issue by arhoy** [tomwilusz/lord-icon-element#4]
I have the following imports 

```
import { loadAnimation } from 'lottie-web';
import { defineLordIconElement } from 'lord-icon-element';
import toggle from '../../../images/lord-icons/toggle.json';
```

And then call the icon in the return like so
  `        <lord-icon animation="hover" src={`${toggle}`}></lord-icon>`

Why is this not working for me? What I am missing?

What is really odd to me is if I replace the last line above with

```
       <lord-icon
            animation="hover"
            src="https://cdn.jsdelivr.net/gh/tomwilusz/lord-icon-element/examples/icons/13-pizza-solid.json"
          ></lord-icon>
```

from the example then it works!

Am I not importing the toggle correctly?

FYI the console log of the imported toggle returns on object, the toggle.JSON file in my images folder.

// console.log
 {v: "5.5.7", fr: 24, ip: 0, op: 9, w: 500, …}

**Comment by baszczewski** [comment]
You can't inject animation content inside element directly with **src** property. Src should containts path to file. 
However there is already supported **icon** property which allows you to use preloaded icons without redundant requests.

Just look for our example:

https://github.com/tomwilusz/lord-icon-element/blob/master/examples/example2.js
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/example2.html

**Comment by arhoy** [comment]
Thanks for your reply @baszczewski . I am still a bit confused on the process. Please bear with me.

1. Does the .json file contain the animation ?
2. Do you have an example with React?
3. I use npm lord-icon-element, should I just use then
`import { defineLordIconElement, LordIconElement } from 'lord-icon-element';`

4. This code below I am getting lottie is not defined.

```
// load sample icons
(async () => {
  LordIconElement.registerIcon('first', await loadIcon('36-bulb-idea-outline'));
  LordIconElement.registerIcon(
    'second',
    await loadIcon('9-cloud-settings-outline'),
  );
})();

// register element
defineLordIconElement(lottie.loadAnimation);
```

Thank you for your assistance and patience, it is my first time trying to load in animated icons using a .json.

**Comment by baszczewski** [comment]
1. Yep. Single .json contains animation. 
2. Unfortunately not. 
3. Yes, but remember also about _lottie-web_ library (I see that you import it in first post but not in next one). 
4. Yes, because you need to import lottie-web which contains internal animation player. We have some reasons why this library is provided without build in this player.

**Comment by arhoy** [comment]
Thank you, I am still having issues. 

loadIcon is not defined. Where do I import this from?

**Comment by baszczewski** [comment]
**LordIconElement** is exported from main point of our library:
https://github.com/tomwilusz/lord-icon-element/blob/master/src/lord-icon-element.ts

Static methods (like registerIcon) on this element could be used to provide preloaded icons (provided from custom source) or new kind of animations / interactions with icons.

**Comment by arhoy** [comment]
So I did the following
import { loadAnimation, loadIcon } from 'lottie-web';
import { defineLordIconElement, LordIconElement } from 'lord-icon-element';

But I get
Unhandled Rejection (TypeError): Object(...) is not a function

Not really sure what I should be looking for in the URL above, could you please explain?

**Comment by baszczewski** [comment]
Why you import "loadIcon" from lottie-web? This external library provide only player for animations.

Please provide complete example of your's code.

**Comment by arhoy** [comment]
Hi here is a complete example. I tried to upload to codesandbox but having some issues

```
// nav.js
import React, { useState } from 'react';
import { Link } from 'gatsby';
import { FaAlignRight } from 'react-icons/fa';
import styled from '@emotion/styled';
import { loadAnimation, loadIcon } from 'lottie-web';
import { defineLordIconElement, LordIconElement } from 'lord-icon-element';

import { MobileMenu1 } from '../menus/mobileMenu1';

import toggle from '../../../images/lord-icons/toggle.json';

// register lottie and define custom element
defineLordIconElement(loadAnimation);

const Header = styled.header`
  margin-top: 2rem;
  color: ${props => props.theme.colors.white};
  position: relative;
  padding: 1rem 0;
  background: transparent;
  display: grid;
  grid-template-columns: 1fr;

  & img {
    & .static {
      position: absolute;
      background: black;
      display: none;
    }
  }
`;

const HeaderTop = styled.div`
  grid-column: 1/-1;
  display: flex;
  justify-content: space-around;
  align-items: center;
`;

const LogoLink = styled(Link)`
  padding: 0;
  margin: 0;
`;
const Logo = styled.span`
  & i {
    font-weight: bold;
    color: ${props => props.theme.colors.white};
  }
  & ${LogoLink} {
    text-decoration: none !important;
    font-size: 3rem;
    line-height: 2.4rem;
  }
`;

const LogoSpan2 = styled.span``;

const BurgerIcon = styled(FaAlignRight)`
  cursor: pointer;
`;

// load sample icons
(async () => {
  LordIconElement.registerIcon('first', await loadIcon('36-bulb-idea-outline'));
  LordIconElement.registerIcon(
    'second',
    await loadIcon('9-cloud-settings-outline'),
  );
})();

const Nav = () => {
  const [mobileMenuOpen, setMobileMenu] = useState(false);

  const mobileMenuHandler = () => {
    setMobileMenu(prevState => !prevState);
  };

  return (
    <>
      <Header>
        <HeaderTop>
          <Logo>
            <LogoLink to="/">
              <i>
                <LogoSpan2>Zeitlify</LogoSpan2>
              </i>
            </LogoLink>
          </Logo>
          <BurgerIcon onClick={mobileMenuHandler} />
          {/* <img className="static" src={cloud} alt="Otter dancing with a fish" /> */}
          <MobileMenu1
            display={mobileMenuOpen.toString()}
            mobileMenuHandler={mobileMenuHandler}
          />
        </HeaderTop>
        <lord-icon
          animation="hover"
          src="https://cdn.jsdelivr.net/gh/tomwilusz/lord-icon-element/examples/icons/13-pizza-solid.json"
        ></lord-icon>
      </Header>
    </>
  );
};

export default Nav;
```

**Comment by baszczewski** [comment]
I still see invalid line:
```js
import { loadAnimation, loadIcon } from 'lottie-web';
```
loadIcon is a part of example (not any of libraries):
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/example2.js

**Comment by arhoy** [comment]
I don't understand do I need to replace lordIcon with something else?

**Comment by baszczewski** [comment]
I just remind you about invalid import (loadIcon) from 'lottie-web' and future usage of it with async code (just remove it).

Other parts of your's code looks good in first look.
