### ISSUE TITLE
Not sure how to use this with Next.js / React

### ISSUE THREAD

**Issue by mellson** [tomwilusz/lord-icon-element#5]
I purchased your awesome icons, and I'm trying to get them to work in a Nextjs app.
But I'm not sure how.

React examples would be much appreciated.

I'm getting: `SyntaxError: Cannot use import statement outside a module` for `module.exports = require("lord-icon-element");`

When I try to use this in Nextjs.

I have tried the abandoned library [react-lottie](https://github.com/chenqingspring/react-lottie), and that works fine. But I'd rather use your library, just can't figure out how to do that 🤔

**Comment by baszczewski** [comment]
Hi. You have to use native modules or some kind of bundler to import library. 
I am not sure how your's project looks like and what dependencies uses but with webpack it is quite easy. Just look inside method used to produce released version of library from built TypeScript:
https://github.com/tomwilusz/lord-icon-element/blob/master/webpack.config.js
https://github.com/tomwilusz/lord-icon-element/blob/master/release/lord-icon.js

**Comment by mellson** [comment]
Hi @baszczewski thanks for the reply 👍 

I am using vanilla Nextjs 9.3. And not really sure that ejecting and changing the module setup would be a good idea.

Is it possible you could provide a React sample of how to use the plugin?

**Comment by baszczewski** [comment]
As I see in documentation NextJS supports native modules.
https://nextjs.org/docs/advanced-features/dynamic-import

Probably you should use import syntax rather than require. Could you check it?

**Comment by mellson** [comment]
Thanks for the quick follow up - I am using import

**Comment by baszczewski** [comment]
> Thanks for the quick follow up - I am using import

And it's works now?

**Comment by mellson** [comment]
No, I've been using import all along. When I use import it throws the error.

**Comment by baszczewski** [comment]
Could you share complete example of your use case?

**Comment by mellson** [comment]
Of course - I've uploaded a barebones nextjs app here: https://github.com/mellson/lord-icon-nextjs-sample

You can find the lord-icon import in this page: https://github.com/mellson/lord-icon-nextjs-sample/blob/master/pages/index.js

I think this could be related to Nextjs SSR / SSG behaviour where it tries to render the page on the server.

**Comment by mellson** [comment]
@baszczewski it was indeed the SSR capabilities of Nextjs that is throwing the error. So I was able to fix it using your component as a dynamic import - I've updated the example above.

So this issue can be closed. Even though it would be nice with a version of the package that works out-of-the box with Nextjs.

Thanks for your help!

**Comment by mellson** [comment]
btw - should I leave the example for future reference? it includes `1-cloud-outline.json` so maybe it's violating some license / terms of use if we leave it?

**Comment by baszczewski** [comment]
I'm glad you found a solution. This example could be helpful for other people so I suggest to leave it but with other (free) icon: https://lordicon.com/free-icons

**Comment by mellson** [comment]
Ok I'll update the sample. Do you have a link to a free icon? I've tried signing up on the free-icons page but nothing happens.

**Comment by baszczewski** [comment]
So you can use icon from this repository with url directly:
https://cdn.jsdelivr.net/gh/tomwilusz/lord-icon-element/examples/icons/13-pizza-solid.json

**Comment by mellson** [comment]
Thanks, I've updated the sample 👍

**Comment by baszczewski** [comment]
And I thank you for awesome sample.

**Comment by frankie567** [comment]
@mellson Your example was *super* useful! Thanks 👏
