### ISSUE TITLE
Editing with lottiefiles editor not working

### ISSUE THREAD

**Issue by mellson** [tomwilusz/lord-icon-element#6]
In example 4 it says to use the lottiefiles editor for changing colors.

> Attention: it is recommended to prepare icons in the desired colors. Replacing the palette and params in fly can be very heavy and is supported only by icons from lordicon.com.

But when I try to load any of the JSON files into the lottiefiles editor it shows errors on almost all layers. And changing the colors does not have any effect (it works on other lotties files).

<img width="934" alt="CleanShot 2020-04-14 at 23 16 24@2x" src="https://user-images.githubusercontent.com/167574/79275164-fbf40b80-7ea5-11ea-9603-837b17c7c9ec.png">

**Comment by baszczewski** [comment]
Ping @tomwilusz

**Comment by tomwilusz** [comment]
@mellson, unfortunately, we are not supporting the color change of our icons via Lottie editor anymore. Soon we will introduce our own Lordicon Editor where you will be able to easily change color, stroke size and a ton of other features too.

**Comment by mellson** [comment]
@tomwilusz nice, I look forward to that
