### ISSUE TITLE
How to control animation?

### ISSUE THREAD

**Issue by caiotarifa** [tomwilusz/lord-icon-element#8]
I didn't find it in the documentation, but how can I control the start of an animation? And the reverse?

I.e. animating a menu icon when click.

**Comment by baszczewski** [comment]
Hi. I am not sure what would you like to achieve but we've already provided sample code to create a custom animation:
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/custom-animations.js
https://github.com/tomwilusz/lord-icon-element/blob/master/examples/custom-animations.html
With that method we can animate two states of menu animation. 

Of course you can control animation playback from any part of your's JavaScript code (LordIconElement provide access to animation instance): https://github.com/tomwilusz/lord-icon-element/blob/47454aa648ca9887dbb6f08b4040dbc369f276a3/src/main/element.ts#L287

**Comment by caiotarifa** [comment]
Sorry, but It is not clear how can I play/pause the animation using JS.

**Comment by baszczewski** [comment]
Pseudo code:
```js
document.getElementById('myLordIconElement').connectedAnimation.play();
```

Advance use case needs to some code study unfortunately. But for your request start from checking examples.

**Comment by caiotarifa** [comment]
```js
import { loadAnimation } from 'lottie-web'
import { defineLordIconElement, BasicAnimation, LordIconElement } from 'lord-icon-element'

class Play extends BasicAnimation {
  ready () {
    this.play()
  }
}

LordIconElement.registerAnimation('play', Play)
defineLordIconElement(loadAnimation)
```

This is what I was trying to do. I would be happy to see it as an official animation. Just play.

**Comment by baszczewski** [comment]
@caiotarifa 
You's example is probably ok. Just keep in mind that animation will play only once, and in custom element animation property you have to use registered by you "play". 

Here you have official, supported "auto" animation, which provide some extra functionalities like loop controlled by JS:
https://github.com/tomwilusz/lord-icon-element/blob/master/src/animations/auto.ts

**Comment by caiotarifa** [comment]
Yes, that I wanted is "just play once". Using `auto`, I found how to control the delay, but not the loop.

**Comment by baszczewski** [comment]
> Yes, that I wanted is "just play once". Using `auto`, I found how to control the delay, but not the loop.

We don't have animation with single play time (without any events like mouse in / click) but yours code look ok. 
"Auto" unfortunately don't support disable of loop.

**Comment by AllenEllis** [comment]
> ```js
> document.getElementById('myLordIconElement').connectedAnimation.play();
> ```

This fails for me - `connectedAnimation` on the `<lord-icon>` element is undefined. Were you meaning to imply that that's a method we could create?

I'd love to simply execute the animation once from vanilla Javascript.

**Comment by baszczewski** [comment]
> > ```js
> > document.getElementById('myLordIconElement').connectedAnimation.play();
> > ```
> 
> This fails for me - `connectedAnimation` on the `<lord-icon>` element is undefined. Were you meaning to imply that that's a method we could create?
> 
> I'd love to simply execute the animation once from vanilla Javascript.

Sorry for the long time to response. API was changed in one of our release. Animation was renamed to trigger in our naming. Consistently object to control animation is available now on "connectedTrigger" property. 

We are working to provide better help, API pages in close future.
